apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-stub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata: 
      name: nginx
      labels:
        app: nginx-stub
    spec:
      containers:
      - name: nginx-stub
        image: dmitry79/nginx_stub:0.0.1
        ports:
         - containerPort: 80
      - name: sidecar-container
        image: dmitry79/nginx-prometheus-exporter:0.9.0
        args: ["-nginx.scrape-uri=http://localhost/basic_status"]
