apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-svc-mon
  labels:
    app: nginx-stub
spec:
  selector:
    matchLabels:
      app: nginx-stub
  endpoints:
  - port: metrics
