prometheusOperator:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool

prometheus:
  prometheusSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
    nodeSelector:
      cloud.google.com/gke-nodepool: infra-pool
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
      cert-manager.io/acme-challenge-type: http01
    hosts:
       - prometheus.104.154.89.14.nip.io
    path: /
    tls:
     - secretName: prometheus.104.154.89.14.nip.io
       hosts:
       - prometheus.104.154.89.14.nip.io

alertmanager:
  alertmanagerSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
    nodeSelector:
      cloud.google.com/gke-nodepool: infra-pool

grafana:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
      cert-manager.io/acme-challenge-type: http01
    hosts: 
       - grafana.104.154.89.14.nip.io
    path: /
    tls:
     - secretName: grafana.104.154.89.14.nip.io
       hosts:
       - grafana.104.154.89.14.nip.io
  additionalDataSources:
      name: Loki
      type: Loki
      url: http://loki:3100/
      access: direct

prometheus-node-exporter:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool

kube-state-metrics:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool
